blockchain/Liquidity pool.md

blockchain: fix liquidity pool

---

Engineering/Entities in Domain Driven Design.md

writing: entities in domain-driven design

---

Engineering/C4 diagrams.md

An engineering introduction to C4 diagrams from our research group software modeling and architecture.
- Derivative of [A deliverable for designing a system for a video streaming platform startup](https://polished-voyage-ff0.notion.site/A-deliverable-for-designing-a-system-for-a-video-streaming-platform-startup-ed88485585fc46ba8f2f3ad97a65b376)

engineering: brief intro to c4 diagrams

---

Engineering/ACID model.md
Engineering/BASE model.md
Engineering/CAP theorem.md
Engineering/Service-based architecture.md

This PR introduces some notes and ideas of service-based architecture taken from our research group Software modeling and architecture. The majority of the concepts from service-based architecture is taken from the book *Fundamentals of Software Architecture: An Engineering Approach* as well as blog articles from Mark Richard (of the same author).
The translation of some of the ideas here proposed to our brainery are also from this post:
https://polished-voyage-ff0.notion.site/A-deliverable-for-designing-a-system-for-a-video-streaming-platform-startup-ed88485585fc46ba8f2f3ad97a65b376
This PR also unatomically introduces the BASE database model as a relation link in service-based architecture. The related train of notes are as follows:
- ACID model
- BASE model
- CAP theorem
These unatomic …

engineering: service-based architecture

---

Writing/Question tree.md

This PR introduces a brainery note for question trees. This is taken 1 for 1 from our research group notes at Software modeling and architecture. There isn't a standardized name for this style of note-taking and research writing, as it is a derivative of an approach to decision trees, but used to ask questions and outline potential answers or approaches.

writing: question tree

---

CONTRIBUTING.md

This PR introduces a `CONTRIBUTING.md` file for use with this git repository. It also entails the manual of style we use for our notes here as well.

docs: create CONTRIBUTING document

---

Engineering/useEffect double calls in React 18.md

engineering: useEffect double calls in React 18

---

Blockchain/Foundational topics/Blocks.md
Blockchain/Foundational topics/PoS.md
Blockchain/Foundational topics/Smart Contract.md
Blockchain/Foundational topics/Topics.md

Create some Foundational topics for blockchain developer

Foundational topics for blockchain

---

Blockchain/NFT Fractionalization.md

blockchain: NFT Fractionalization

---

Blockchain/Foundational topics/Distributed systems.md

The fundamental topic for blockchain "Distributed systems on blockchain"

blockchain: Distributed systems

---

CONTRIBUTING.md

chore: update convention details pr commit

---

Engineering/JavaScript modules.md

engineering: javascript modules

---

Design/What Screens Want.d
Design/What Screens Want.md

Publishing "What Screens Want" notes

design: what screens want

---

Engineering/Domain Model in Domain Driven Design.md
Engineering/Domain model in Domain Driven Design.md

engineering: domain model in DDD

---

Blockchain/Anchor framework.md

Format the document before we publish it

chore: format Anchor framework tutorial

---

CONTRIBUTING.md

Since we are a bit more careful with how we organize areas of knowledge, this update makes sure that we don't discourage contributors from creating their own folders or listing items in existing nested folders.

docs: update nested folder notice

---

Design/UI History

A good user interface should make it possible to complete any task quickly and with enjoyment. The user interface that you see on your MacOS or Windows PC has taken a long time to develop. This essay will briefly examine the changes in computer interface design over the last 30 years.

Design: UI History

---

Engineering/Atomic package in Golang.md
Engineering/Backend/Atomic package in Golang.md

engineering: atomic package in golang to solve race-condition

---

Engineering/Backend/Atomic package in Golang.md

fix: format atomic post code

---

Engineering/Frontend/Dark mode flickers a white background for a fraction of a second.md

Met the issue when working on the NFT aggregator project.

engineering: dark mode flickers a white background issue

---

Engineering/Frontend/CSS in JS.md

Quick note about CSS in JS

---

Engineering/Double-entry accounting.md

engineering: double-entry accounting

---

Engineering/Concurrency in Javascript.md

engineering: concurrency in javascript

---

Engineering/Mobile/Swift 5.4 @resultBuilder.md

The second part of Building UI with UIKit using Builder pattern (DSL style)

engineering: Wrap UIKit using Swift 5.4 @resultBuilder

---

Engineering/Frontend/CSS Container Queries.md

engineering: CSS container queries

---

Engineering/Frontend/HSL Color.md

engineering: HSL colors

---

Blockchain/Foundational topics/ZK.md
Blockchain/Foundational topics/Zero-knowledge Proofs.md

blockchain: zero-knowledge proofs

---

Engineering/Frontend/Mitigate blocking the main thread.md

frontend: mitigate blocking the main thread

---

Engineering/Mobile/Kotlin coroutine.md

mobile: Kotlin coroutine

---

Engineering/Mobile/Secret Management on iOS.md

engineering: secret management on ios

---

Engineering/Frontend/Pure CSS Parallax.md

frontend: pure css parallax

---

Engineering/Mobile/Kotlin coroutine.md

fix: typo kotlin coroutine

---

CONTRIBUTING.md
Map of Content.md

docs: add moc and contributing docs

---

Engineering/Mobile/Stateless and Stateful Widgets in Flutter.md
Engineering/Mobile/flutter/stateless_statefull.md

flutter: stateless and stateful widget

---

Engineering/Mobile/The structure of the command line app.md

The structure of the CommandLine tool app

---

Engineering/Management/Pomodoro Technique.md
Writing/Twelve principles of time management.md

engineering: pomodoro technique

---

Engineering/Frontend/Build polymorphic React components with Typescript.md
Engineering/Frontend/Build polymorphism React components with Typescript.md

engineering: create note about building polymorphic components

---

Engineering/Management/Story point estimation.md

[Engineering] Management: Story point estimation

---

Engineering/Frontend/WAI-ARIA.md

frontend: wai-aria

---

Engineering/Mobile/Kotlin coroutine lifecycle.md

mobile: kotlin coroutine lifecycle

---

Engineering/Frontend/An Introduction to Atomic CSS.md

frontend: an introduction to atomic css

---

Engineering/Frontend/Intro to IndexedDB.md

frontend: intro to IndexedDB

---

Engineering/Management/How one product team works when having incident.md

[Engineering] Management: How to solve an incident from the product team

---

Engineering/Backend/libcluster in elixir.md

engineering: libcluster for elixir scaling in K8s

---

Engineering/Backend/pg in elixir.md

engineering: pg library in elixir to solve the communication services problem

---

Engineering/Data/Introduction to Apache Hive.md

- A brief introduction about Apache Hive
- Motivation, History
- Some DDL, DML syntax with Hive

engineering: Introduction to Apache Hive

---

Engineering/Mobile/Scale up Application using Jetpack Navigation.md

- Advantage/ disadvantages of jetpack navigation
- How to fix disadvantage to scale up application using navigation component

mobile: scale up application with jetpack navigation

---

Blockchain/Solana Account.md

A small note about Solana account

---

.gitmodules

chore: add challenge submodule

---

Blockchain/§ Blockchain MOC.md
_templates/MOCs/Template - Create Blockchain MOC.md

docs: label frontmatter and create basic MOC for Blockchain

---

Blockchain/Layer 2.md

blockchain: Layer 2

---

Engineering/Event sourcing overview.md

- Add event sourcing overview
- Problem statement for the e-commerce platform 
- Introduce event sourcing's `event`, `event store`, `state` concepts

engineering: Event sourcing overview

---

Blockchain/zk-SNARKs.md

blockchain: zk-SNARKs

---

Engineering/Mobile/Data race and race condition.md

Data race and race condition

---

Engineering/Data/Data Vault modelling

// Put in link to Git Issue
// Use [Licecap](http://www.cockos.com/licecap/) to share a screencast gif.
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?

Update final data vault model

---

Engineering/Debugging in JavaScript.md
Engineering/Frontend/Parse, don't vaildate in TypeScript.md

frontend: Parse, don't validate in TypeScript

---

Engineering/Management/Difference betwwen Project-Program-Portfolio manager.md

- Difference between manager roles

Management: Project Manager, Program Manager, and Portfolio Manager

---

Engineering/Frontend/Validation with Zod.md

engineering: Validation with Zod

---

Engineering/Law of Demeter.md

engineering: Law of Demeter

---

Engineering/Frontend/When should we use useReducer instead of useState?.md

engineering: when should we use useReducer instead of useState

---

Engineering/DevOps/Testing AWS services locally with LocalStack.md

devops: testing aws services locally with localstack

---

Engineering/Profiling in Go.md

engineering: Profiling in Go

---

Engineering/SOLID principles.md

engineering: solid principles

---

Engineering/Frontend/Retain scroll position in infinite scroll.md

engineering: retain scroll position in infinite scroll

---

Engineering/Backend/Database Locking.md

engineering: database explicit locking

---

Engineering/Redis streaming.md

engineering: redis streaming

---

Engineering/Frontend/Retain scroll position in infinite scroll.md

chore: update retain scroll position in infinite scroll article

---

Engineering/Redis streaming concurrency with master, consumers.md

engineering: redis streaming concurrency with master, consumers pattern

---

README.md

chore: add README badges

---

Engineering/AI/Select Vector Database for LLM.md

ai: select vector database for LLM application

---

Engineering/Frontend/URL formats for sharing via social networks.md

engineering: url formats for sharing via social networks

---

Engineering/Frontend/Scroll-driven animations.md

frontend: scroll-driven animations

---

Engineering/Frontend/A Fragment Colocation Pattern with React & Apollo GraphQL.md

frontend: a fragment colocation pattern

---

Engineering/Frontend/Applying Mock Service Worker (MSW) for Seamless Web Development.md

frontend: applying Mock Service Worker (MSW) for Seamless Web Development

---

Engineering/Backend/Testing Made Simple Best Practices for Golang Test.md

backend: best practise for golang testing

---

Engineering/Backend/Test Doubles.md

backend: test doubles

---

Engineering/Frontend/Optimizing images with next image for improved performance.md

frontend: optimizing images with next image for improved performance

---

Engineering/URL Redirect vs. Rewrite; What’s the difference?.md

engineering: URL Redirect vs. Rewrite; What’s the difference?

---

Engineering/Backend/SQL Sargable Queries and Their Impact on Database Performance.md

backend: SQL Sargable Queries and Their Impact on Database Performance

---

_memo/how-to-set-up-environment-for-editing-memo.md

// Put in link to Git Issue
// Use [Licecap](http://www.cockos.com/licecap/) to share a screencast gif.
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?

create article: how to set up environment

---

_memo/devbox-a-world-before-docker.md
_memo/devbox-docker-adoption-and-challenges.md
_memo/devbox-nix-and-our-devbox-adoption.md

fix: devbox typo

---

_memo/understanding-saving-investing-and-speculating-key-differences-and-strategies.md

create new note playground/memo

feat: understanding saving investing ogif 

---

01_literature/builder-design-pattern.md
01_literature/prototype-design-pattern.md
01_literature/singleton-design-pattern.md

fix: bump memo publish date

---

01_literature/devbox-a-world-before-docker.md
01_literature/devbox-docker-adoption-and-challenges.md
01_literature/devbox-local-development-env.md
01_literature/devbox-nix-and-our-devbox-adoption.md

Devbox 4: Local Development Environment

engineering: devbox p4

---

00_fleeting/Proximal Policy Optimization.md

ai: Proximal Policy Optimization

---

00_fleeting/Rust Trait.md

Add Rust Trait.md

---

00_fleeting/Rust Trait.md
01_literature/error-handling-in-rust.md

engineering: error handling on Rust

---

00_fleeting/go-weekly-511.md

engineering: goweekly 511

---

00_fleeting/go-commentary-jul-12.md

engineering: go commentary in jul 08 week

---

00_fleeting/202407191200 - Subscription Pricing Models.md
00_fleeting/subscription-pricing-models.md

docs: fleeting note about pricing models

---

00_fleeting/go-commentary-aug-16.md

engineering: go commentary in aug 16

---

00_fleeting/go-commentary-aug-30.md

engineering: go commentary in aug 30

---

01_literature/Engineering/AI/journey-of-thought-prompting.md

memo: journey of thought prompting

---

01_literature/Building LLM system/§ Building LLM System.md

add building LLM system MOC

---

00_fleeting/go-commentary-sep-13.md

engineering: go commentary in sep 13

---

go/how-to-use-go-in-enterprise.md
go/who-using-golang-in-enterprise.md

go: enterprises use go

---

go/why-enterprise-chose-java.md

go: why enterprise chose java

---

01_literature/design-file-sharing-system-part-1-directory structure.md
01_literature/design-file-sharing-system-part-2-permission-and-password.md

memo: update link in design sharing file system

---

devbox/introduction/The reason for being.md
devbox/introduction/Why Devbox But Not Nix.md
devbox/introduction/¶ Devbox Plugins.md
devbox/introduction/¶ Devbox Services.md
devbox/introduction/¶ Devbox.md
devbox/introduction/¶ Nix Flakes.md
devbox/introduction/¶ Nix Shell.md
devbox/research/Content-addressable storage in Docker.md
devbox/research/≈ Nix in building Docker images.md
devbox/story/devbox-production-success-story.md

fix: redundant posts titles

---

01_literature/Engineering/AI/Prevent prompt injection.md
01_literature/Engineering/AI/prevent-prompt-injection.md

memo: prevent prompt injection

---

01_literature/Building LLM system/prevent-prompt-injection.md
01_literature/Building LLM system/§ Building LLM System.md

fix: link memo to LLM MOC

---

01_literature/Building LLM system/evaluation-guideline-for-LLM-application.md

docs: evaluation guideline for llm application

---

01_literature/Building LLM system/evaluation-guideline-for-LLM-application.md

Fix format docs evaluation guideline for llm application

---

00_fleeting/go-commentary-sep-27.md

engineering: go commentary in sep 27

---

00_fleeting/go-commentary-oct-04.md

engineering: go commentary in oct 04

---

AI/Building LLM system/intent-classification-by-LLM.md
AI/Building LLM system/§ Building LLM System.md

memo: intent classifier

---

go/weekly/go-commentary-oct-11.md

engineering: go commentary in oct 11

---

go/weekly/go-commentary-oct-11.md

chore: add title, desc

---

go/weekly/go-commentary-oct-11.md

chore: fix format title

---

Frontend/react/code-splitting.md
Frontend/react/component-communication-and-decoupling.md
Frontend/react/component-composition-patterns.md
Frontend/react/design-system-integration.md
Frontend/react/hook-architecture.md
Frontend/react/rendering-strategies.md
Frontend/react/state-management-strategy.md
Frontend/react/testing-strategies.md

fundamentals of building apps with React

---

go/weekly/nov-01.md

engineering: go commentary in nov 01

---

go/weekly/nov-08.md

engineering: go commentary in nov 08

---

go/weekly/nov-15.md

engineering: go commentary in nov 15

---

01_literature/reconstructing_trading_pnl_data_pipeline_approach.md

- This PR addresses the issue of missing historical PnL data, which is critical for performance analysis, compliance, and strategy validation.
- Instead of modifying the existing codebase, a separate data pipeline was developed to reconstruct the missing PnL data from available sources (trading history, fees, market prices).
- The blog post outlines the challenges faced, the data pipeline architecture, implementation details, optimization strategies, and quality assurance measures.
- The data pipeline approach provides a scalable, maintainable solution to the problem of missing historical PnL data.
- No new dependencies were introduced.

engineering: reconstructing trading PNL data using data pipeline 

---

01_literature/enhancing-cryptocurrency-transfer-logger.md

**What's this PR do?**
This PR adds a detailed case study blog post titled "Transfer Mapping: Enhancing Loggers for Better Transparency" that explains the approach and implementation for enhancing the cryptocurrency transfer logging system to provide better transparency and traceability for users and developers.

engineering: enhancing cryptocurrency transfer logger

---

Use Cases/ai-ruby-travel-assistant-chatbot.md

chore: add ai ruby travel assistant case study

---

Use Cases/ai-powered-monthly-project-reports.md
Use Cases/ai-ruby-travel-assistant-chatbot.md
Use Cases/binance-transfer-matching.md
Use Cases/bitcoin-alt-performance-tracking.md
Use Cases/building-chatbot-agent-for-project-management-tool.md
Use Cases/building-data-pipeline-ogif-transcriber.md
Use Cases/centralized-monitoring-setup-for-trading-platform.md
Use Cases/crypto-market-outperform-chart-rendering.md
Use Cases/data-archive-and-recovery.md
Use Cases/database-hardening-for-trading-platform.md
Use Cases/enhancing-cryptocurrency-transfer-logger.md
Use Cases/implement-binance-future-pnl-analysis-page.md
Use Cases/migrate-normal-table-to-timescale-table.md
Use Cases/persist-history-using-data-snapshot-pattern.md
Use Cases/reconstructing_trading_pnl_data_pipeline_approach.md

fix: usecases formatting

---

.github/workflows/markdown-lint.yml

fix: remove artifacts on failed

---

topics/engineering/database-designs-for-multilingual-apps.md

Spotted and fixed a few wording hiccups:
`slighly` - `slightly`
`diffrent` - `different`
- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?

polishing docs: error fixes for clarity
