dwarvesf/research

- Engineering/C4 diagrams.md
This PR adds missing author metadata for the C4 diagram brainery note.
> fix: append author name for C4 diagrams

- Engineering/State machines/Finite-state automata.md
- Engineering/State machines/Reducers.md
- Engineering/State machines/State explosion.md
This PR adds a few introductory notes for state machines. Since the family topic on finite-state automata is quite large, this PR also creates a folder `State machine` to organize the notes there.
> engineering: introductory articles on state machines

- Engineering/Finite-state automata.md
- Engineering/Finite-state transducer.md
- Engineering/Mealy machine.md
- Engineering/Moore machine.md
- Engineering/Reducers.md
> engineering: finite-state transducers + mealy and moore machines

- Engineering/Mobile/Kotlin coroutine.md
> fix: typo in kotlin coroutine article

- Engineering/Frontend/Build polymorphic React components with Typescript.md
> chore: fix typos

- Blockchain/Anchor framework.md
- Blockchain/Blockchain Bridge.md
- Blockchain/Foundational topics/Blocks.md
- Blockchain/Foundational topics/PoS.md
- Blockchain/Foundational topics/Smart Contract.md
- Blockchain/Foundational topics/Topics.md
- Blockchain/Liquidity pool.md
- Blockchain/Multisign wallet.md
- Blockchain/NFT Fractionalization.md
- Design/UI History.md
- Design/UX Research/Triple S of UX in Web3.md
- Design/What Screens Want.md
- Engineering/Concurrency in Javascript.md
- Engineering/Frontend/Build polymorphic React components with Typescript.md
- Engineering/Frontend/CSS Container Queries.md
- Engineering/Frontend/HSL Color.md
- Engineering/Frontend/useEffect double calls in React 18.md
- Engineering/Management/Stream-aligned team.md
- Writing/Question tree.md
- Writing/State, Explain, Link.md
- _reports/Brainery Notes All Notes.md
- _reports/Brainery Notes Report.md
- _reports/Fleeting Notes All Notes.md
- _reports/Fleeting Notes Report.md
This PR introduces an internal `_reports` folder to keep track of current brainery entries we've made so far that has an attributed `author` or `discord_id` frontmatter key. This may be used for aggregation collection of data in the future.
---
> docs: add dataview reports for brainery + fleeting notes

- .gitignore
- _templates/Run - Publish Entry to Discord.md
Prior art included a method to do this through Obsidian Plugins. Since the code for this is not as complicated and the plugin itself may be deprecated in the future, I have chosen to implement it as a small script in Templater.
This script requires a file `_scripts/_env.md` with frontmatter containing your discord webhooks through a prefix/suffix `discord_webhook`:
When you run the templater command, a prompt will include all `discord_webhook` frontmatter to select to which server/channel you wish to push to:
> feat: brainery submission discord

- Engineering/Introducing HTMX - Navigating the Advantages and Concerns.md
> engineer: intro to HTMX and its pros, cons

- _memo/builder-design-pattern.md
> memo: builder design pattern

- go/weekly/dec-13.md
> engineering: go commentary in dec 13

- Blockchain/zk-SNARKs.md
Hi! I fixes a dead link in the `zk-SNARKs.md` file. The old link pointed to a deprecated or non-existent page for Vitalik Buterin's blog post on using SNARKs. It has been updated to the correct and current URL.
> docs: update 404 link zk-SNARKs.md

- README.md
Noticed a grammar mistake in the badge text: **"make by dwarves"** should be **"made by dwarves"**.
Fixed it in the HTML snippet. Now it looks correct! ✅
> docs: fixed typo in Badge

- Blockchain/ton_blockchain_of_blockchains.md
I’ve corrected a small grammatical mistake in the text. The sentence now reads "To understand what actually happens under these shiny names of technologies" instead of "happen."
The issue was that the verb "happen" should be in the third-person singular form "happens."
> docs: Fixed grammatical error in the sentence structure

- Frontend/Atomic Design Pattern.md
Noticed a couple of small grammar mistakes in the atomic design section. Fixed them to improve readability.
> docs: fixed typos in atomic design section

- Use Cases/ai-powered-monthly-project-reports.md
Spotted a small typo and a grammar issue in the documentation.
"Layed" should be "**laid**," and "makes" should be "**make**" to match the plural subject "foundations."
Now it reads correctly 🚀
> docs: Fix typo and subject-verb agreement in documentation

- devbox/research/Unstable package installation.md
I noticed a few small typos and grammatical errors that could make the text clearer and more polished.
Fixed them to improve readability.
- Added missing apostrophe in "let's suppose"  
- Added "the" in "we have the following Dockerfile"  
- Fixed preposition usage in "the environment in which your application is running"  
- Removed an extra phrase in "more than one solution pops into your mind"  
Hope this helps!
> docs: Fixing typos and grammar for better clarity

- Zettelkasten/How to Take Smart Notes/Brainstorming surfaces available ideas, not new ideas.md
- Zettelkasten/How to Take Smart Notes/Decontextualize ideas to make them new.md
- Zettelkasten/How to Take Smart Notes/Design environments to facilitate behaviours.md
I’ve corrected a few minor typos and grammar issues in the following files:
- In *`Brainstorming surfaces available ideas, not new ideas.md`*, I fixed "The hold us back like anchors" to "They hold us back like anchors".
- In *`Decontextualize ideas to make them new.md`*, I changed "as they actual appear" to "as they actually appear".
- In *`Design environments to facilitate behaviours.md`*, I updated "Designing environments to facilitate desire behaviour" to "Designing environments to facilitate desired behaviour".
These changes should improve readability and clarity.
> docs: Fixed Minor Typos and Grammar Issues Across Multiple Files

- Frontend/HTML inert.md
I’ve updated the link to the "inert" HTML attribute documentation.
The original link to developer.chrome.com was outdated, so I’ve replaced it with the correct one from web.dev.
Everything else remains unchanged.
> docs: Fixed incorrect link to "inert" article

- Writing/Core needs and psychological maneuvers give fictional characters depth.md
I’ve corrected a small typo in the recipe description where "wo ingredients" was written instead of "**two ingredients**."
Now it’s accurate and ready for the readers.
> docs: Fix typo in recipe description

- Use Cases/ai-ruby-travel-assistant-chatbot.md
I noticed a couple of grammatical and stylistic issues and went ahead and fixed them:  
- **"alongside with their team"** → **"alongside their team"** (removed redundancy)  
- **"Both the client and our work has had lasting effects"** → **"Both the client and our work have had lasting effects"** (corrected verb agreement)
> docs: Fix minor grammatical and stylistic errors

- Blockchain/Foundational topics/Blocks.md
I noticed a typo in the fraud prevention message.
It originally said "This prevention fraud" which sounded a bit off. I’ve updated it to "This prevents fraud" for clarity and correctness.
Now the message reads more naturally and communicates the intended meaning better.
> docs: fix typo in fraud prevention message

- Blockchain/Foundational topics/Smart Contract.md
I’ve made some corrections to improve the accuracy of the text:
- In the "Structure of a smart contract" section, changed "Declare variable" to "Declare variables" as it’s more appropriate for the context of declaring multiple variables.
- In the "The advance of smart contracts" section, changed "advance" to "advantages" to reflect the intended meaning.
- In the "The limitation of smart contracts" section, updated "limitation" to "limitations" to align with the fact that multiple limitations are being discussed.
These updates should make the content clearer and more precise.
> docs: Fixed minor text inconsistencies

- Frontend/Dark mode flickers a white background for a fraction of a second.md
I noticed a small typo in the phrase "flicker of white background". It should be "flicker of a white background" to make the sentence grammatically correct. I've updated it accordingly.
> docs: fix typo in "flicker of white background"

- UX Research/Four Theories of Truth.md
There's a small typo:
- **"it it is useful"** → corrected to **"it is useful"** (extra "it").
> docs: typo fix

- UX Research/Landscape of UX research methods.md
I noticed a small typo in the section about UX research methods. The phrase "quantitative method are used" was corrected to "quantitative methods are used" to match the plural form.
> docs: fix typo in the UX research methods section

- AI/Building LLM system/quantization-in-llm.md
- Blockchain/Liquidity pool.md
Gohugo KaTeX formatting differs slightly from standard KaTeX. As we migrate to Next.js, we need to adjust the math formatting to ensure compatibility.
- PR handle Katex: https://github.com/dwarvesf/memo.d.foundation/pull/79
- PR migrate nextjs: https://github.com/dwarvesf/memo.d.foundation/pull/39
> fix: katex format

- 01_literature/Writing/Question tree.md
- 01_literature/Writing/The Six Lines of Gold.md
- 01_literature/Writing/state-explain-link.md
I’ve made some small but important grammar corrections across a couple of files:
- In `01_literature/Writing/state-explain-link.md`, I replaced "in which" with "which" to ensure proper sentence structure.
- In `01_literature/Writing/The Six Lines of Gold.md`, I corrected "the key differences that should we look out for" to "the key differences that we should look out for."
- In `01_literature/Writing/state-explain-link.md`, I removed the extra "about" in the phrase "introduce briefly about what the paragraph will cover," making it "introduce briefly what the paragraph will cover."
These changes should help the text read more smoothly and accurately.
> docs: Fixed grammatical issues in docs

- 01_literature/_how-to-setup-crypto-wallet-to-withdraw-icy.md
Updated the outdated guideline link for withdrawing ICY to point to the correct and existing file under playground/01_literature/how-to-withdraw-icy.
The previous URL was broken, and this fix ensures us
> Fix broken guideline link
